import type { Patient, Doctor, BiomarkerThreshold, Alert } from './types';
import { Biomarker, AlertLevel, AlertStatus, Gender } from './types';

// Biomarkers are ordered to match the DIRUI H11 test strip for consistency.
export const BIOMARKER_THRESHOLDS: Record<Biomarker, BiomarkerThreshold> = {
  [Biomarker.UROBILINOGEN]: { name: 'Urobilinogen', unit: 'µmol/L', normal: v => typeof v === 'number' && v <= 17, caution: v => typeof v === 'number' && v > 17 && v <= 34 },
  [Biomarker.BILIRUBIN]: { name: 'Bilirubin', unit: 'µmol/L', normal: v => v === 'Negative' },
  [Biomarker.KETONE]: { name: 'Ketone', unit: 'mmol/L', normal: v => v === 'Negative', caution: v => v === 'Trace' },
  [Biomarker.BLOOD]: { name: 'Blood', unit: 'Ery/µL', normal: v => v === 'Negative' },
  [Biomarker.PROTEIN]: { name: 'Protein', unit: 'g/L', normal: v => typeof v === 'number' && v < 0.3, caution: v => typeof v === 'number' && v >= 0.3 && v < 1.0 },
  [Biomarker.NITRITE]: { name: 'Nitrite', unit: '', normal: v => v === 'Negative' },
  [Biomarker.LEUKOCYTES]: { name: 'Leukocytes', unit: 'Leuko/µL', normal: v => v === 'Negative' },
  [Biomarker.GLUCOSE]: { name: 'Glucose', unit: 'mmol/L', normal: v => v === 'Negative', caution: v => v !== 'Negative' },
  [Biomarker.SPECIFIC_GRAVITY]: { name: 'Specific Gravity', unit: '', normal: v => typeof v === 'number' && v >= 1.005 && v <= 1.025, caution: v => typeof v === 'number' && (v < 1.005 || v > 1.025) },
  [Biomarker.PH]: { name: 'pH', unit: '', normal: v => typeof v === 'number' && v >= 5.0 && v <= 8.5 },
  [Biomarker.ASCORBIC_ACID]: { name: 'Ascorbic Acid', unit: 'mmol/L', normal: v => typeof v === 'number' && v === 0 },
};

export const doctors: Doctor[] = [
  {
    id: 101,
    name: 'Dr. David',
    avatar: 'https://picsum.photos/seed/drdavid/100/100',
    patientIds: [1, 2, 3, 4, 5, 6, 7],
  },
];

export const patients: Patient[] = [
  {
    id: 1,
    name: 'Eleanor Vance',
    age: 78,
    gender: Gender.FEMALE,
    avatar: 'https://picsum.photos/seed/eleanor/100/100',
    hospital: 'Sahlgrenska',
    contact: { email: 'eleanor.vance@example.com', phone: '555-0101', address: '123 Willow Creek, Gothenburg' },
    caregiver: { name: 'John Vance', relation: 'Son', phone: '555-0102' },
    results: [
      { date: '2023-09-28T08:00:00Z', values: { [Biomarker.UROBILINOGEN]: 10, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.015, [Biomarker.PH]: 6.5, [Biomarker.ASCORBIC_ACID]: 0, }, },
      { date: '2023-09-29T08:00:00Z', values: { [Biomarker.UROBILINOGEN]: 12, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.15, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.021, [Biomarker.PH]: 6.2, [Biomarker.ASCORBIC_ACID]: 0, }, },
      { date: '2023-10-03T08:10:00Z', values: { [Biomarker.UROBILINOGEN]: 20, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Trace', [Biomarker.BLOOD]: 'Trace', [Biomarker.PROTEIN]: 0.3, [Biomarker.NITRITE]: 'Positive', [Biomarker.LEUKOCYTES]: 'Trace', [Biomarker.GLUCOSE]: 5.6, [Biomarker.SPECIFIC_GRAVITY]: 1.028, [Biomarker.PH]: 7.0, [Biomarker.ASCORBIC_ACID]: 0.6, }, },
      { date: '2023-10-07T08:10:00Z', values: { [Biomarker.UROBILINOGEN]: 35, [Biomarker.BILIRUBIN]: 'Positive', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Trace', [Biomarker.PROTEIN]: 1.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Trace', [Biomarker.GLUCOSE]: 'Trace', [Biomarker.SPECIFIC_GRAVITY]: 1.030, [Biomarker.PH]: 7.2, [Biomarker.ASCORBIC_ACID]: 0, }, },
      { date: '2023-10-08T08:00:00Z', values: { [Biomarker.UROBILINOGEN]: 15, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.2, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.020, [Biomarker.PH]: 6.8, [Biomarker.ASCORBIC_ACID]: 0, }, },
    ],
  },
  {
    id: 2,
    name: 'Arthur Pendelton',
    age: 65,
    gender: Gender.MALE,
    avatar: 'https://picsum.photos/seed/arthur/100/100',
    hospital: 'Sahlgrenska',
    contact: { email: 'arthur.p@example.com', phone: '555-0103', address: '45 Oak Avenue, Gothenburg' },
    caregiver: { name: 'Gwen Pendelton', relation: 'Wife', phone: '555-0104' },
    results: [
      { date: '2023-10-08T09:00:00Z', values: { [Biomarker.UROBILINOGEN]: 12, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.035, [Biomarker.PH]: 5.5, [Biomarker.ASCORBIC_ACID]: 0, }, },
      { date: '2023-10-09T09:05:00Z', values: { [Biomarker.UROBILINOGEN]: 10, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.018, [Biomarker.PH]: 5.8, [Biomarker.ASCORBIC_ACID]: 0, }, },
    ],
  },
   {
    id: 3,
    name: 'Beatrice Miller',
    age: 82,
    gender: Gender.FEMALE,
    avatar: 'https://picsum.photos/seed/beatrice/100/100',
    hospital: 'Sahlgrenska',
    contact: { email: 'beatricem@example.com', phone: '555-0105', address: '789 Pine Lane, Mölndal' },
    caregiver: { name: 'SELF', relation: 'N/A', phone: 'N/A' },
    results: [
      { date: '2023-10-08T10:00:00Z', values: { [Biomarker.UROBILINOGEN]: 18, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Trace', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.35, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.028, [Biomarker.PH]: 7.5, [Biomarker.ASCORBIC_ACID]: 0, }, },
      { date: '2023-10-09T10:05:00Z', values: { [Biomarker.UROBILINOGEN]: 20, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Trace', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.4, [Biomarker.NITRITE]: 'Positive', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.029, [Biomarker.PH]: 7.2, [Biomarker.ASCORBIC_ACID]: 0, }, },
    ],
  },
  {
    id: 4,
    name: 'Charles Dickens',
    age: 58,
    gender: Gender.MALE,
    avatar: 'https://picsum.photos/seed/charles/100/100',
    hospital: 'Sahlgrenska',
    contact: { email: 'charles.d@example.com', phone: '555-0106', address: '221B Baker Street, London (Remote)' },
    caregiver: { name: 'Catherine Dickens', relation: 'Wife', phone: '555-0107' },
    results: [ { date: '2023-10-09T11:00:00Z', values: { [Biomarker.UROBILINOGEN]: 15, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.015, [Biomarker.PH]: 6.0, [Biomarker.ASCORBIC_ACID]: 0, }, }, ],
  },
  {
    id: 5,
    name: 'Diana Prince',
    age: 45,
    gender: Gender.FEMALE,
    avatar: 'https://picsum.photos/seed/diana/100/100',
    hospital: 'Kry',
    contact: { email: 'diana.prince@example.com', phone: '555-0108', address: '1 Paradise Island, Remote' },
    caregiver: { name: 'Steve Trevor', relation: 'Partner', phone: '555-0109' },
    results: [ { date: '2023-10-09T12:00:00Z', values: { [Biomarker.UROBILINOGEN]: 16, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Trace', [Biomarker.SPECIFIC_GRAVITY]: 1.022, [Biomarker.PH]: 6.5, [Biomarker.ASCORBIC_ACID]: 0, }, }, ],
  },
  {
    id: 6,
    name: 'Frank Castle',
    age: 52,
    gender: Gender.MALE,
    avatar: 'https://picsum.photos/seed/frank/100/100',
    hospital: 'Kry',
    contact: { email: 'frank.castle@example.com', phone: '555-0110', address: '10 War Zone, New York (Remote)' },
    caregiver: { name: 'SELF', relation: 'N/A', phone: 'N/A' },
    results: [ { date: '2023-10-09T13:00:00Z', values: { [Biomarker.UROBILINOGEN]: 12, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.1, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.010, [Biomarker.PH]: 6.8, [Biomarker.ASCORBIC_ACID]: 0, }, }, ],
  },
  {
    id: 7,
    name: 'Gloria Hernandez',
    age: 68,
    gender: Gender.FEMALE,
    avatar: 'https://picsum.photos/seed/gloria/100/100',
    hospital: 'Kry',
    contact: { email: 'gloria.h@example.com', phone: '555-0111', address: '34 Sunshine Blvd, Miami (Remote)' },
    caregiver: { name: 'Jay Pritchett', relation: 'Husband', phone: '555-0112' },
    results: [ { date: '2023-10-08T14:00:00Z', values: { [Biomarker.UROBILINOGEN]: 14, [Biomarker.BILIRUBIN]: 'Negative', [Biomarker.KETONE]: 'Negative', [Biomarker.BLOOD]: 'Negative', [Biomarker.PROTEIN]: 0.2, [Biomarker.NITRITE]: 'Negative', [Biomarker.LEUKOCYTES]: 'Negative', [Biomarker.GLUCOSE]: 'Negative', [Biomarker.SPECIFIC_GRAVITY]: 1.012, [Biomarker.PH]: 6.2, [Biomarker.ASCORBIC_ACID]: 0, }, }, ],
  },
];

export const alerts: Alert[] = [
    {
        id: 'a1',
        patientId: 1,
        patientName: "Eleanor Vance", 
        message: "Liver function concern. Urobilinogen (35 µmol/L) and Bilirubin (Positive) are high.", 
        level: AlertLevel.HIGH,
        timestamp: "2023-10-07T08:10:00Z",
        status: AlertStatus.ACTIVE,
    },
    {
        id: 'a2',
        patientId: 3,
        patientName: "Beatrice Miller", 
        message: "Possible UTI risk detected. Nitrite is positive.",
        level: AlertLevel.HIGH,
        timestamp: "2023-10-09T10:05:00Z",
        status: AlertStatus.ACTIVE,
    },
    {
        id: 'a3',
        patientId: 2,
        patientName: "Arthur Pendelton", 
        message: "Indication of dehydration. Specific Gravity is high (1.035).",
        level: AlertLevel.MEDIUM,
        timestamp: "2023-10-08T09:00:00Z",
        status: AlertStatus.ACTIVE,
    },
    {
        id: 'a4',
        patientId: 5,
        patientName: "Diana Prince", 
        message: "Glucose detected in urine (Trace). Monitor for potential diabetes.",
        level: AlertLevel.MEDIUM,
        timestamp: "2023-10-09T12:00:00Z",
        status: AlertStatus.ACTIVE,
    },
    {
        id: 'a5',
        patientId: 1,
        patientName: "Eleanor Vance", 
        message: "Kidney function flag. Protein level is high (1.1 g/L).",
        level: AlertLevel.HIGH,
        timestamp: "2023-10-07T08:10:00Z",
        status: AlertStatus.REVIEWED,
    },
];